apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    namespace 'info.jnlm.thermal_camera'

    defaultConfig {
        applicationId "info.jnlm.thermal_camera"
        minSdkVersion 29
        targetSdkVersion 35
        versionCode 4
        versionName "1.3"
    }

    signingConfigs {
        release {
            storeFile file("../release-key.jks")
            storePassword "android"
            keyAlias "release"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
		}
    }
   
    externalNativeBuild {
        ndkBuild {
            path "src/main/cpp/Android.mk"
		}
	}

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'
    // FFmpeg removed - use python/commands.sh to convert raw videos on PC
}

